package adventure.utils;

public class RoomType {
    public static final int CELL = 0;
    public static final int CORRIDOR = 1;
    public static final int LADDERS = 2;
    public static final int LOBBY = 3;
    public static final int LOBBYSOUTH = 4;
    public static final int ENDLOBBY = 5;
    public static final int GARDEN = 6;
    public static final int BASKETCAMP = 7;
    public static final int WALL = 8;
    public static final int BENCH = 9;
    public static final int INFIRMARY = 10;
    public static final int SECRETPASSAGE = 11;
    public static final int PASSAGESOUTH = 12;
    public static final int PASSAGENORTH = 13;
    public static final int GENERATOR = 14;
    public static final int LADDER = 15;
    public static final int AIRDUCT = 16;
    public static final int AIRDUCTEAST = 17;
    public static final int AIRDUCTNORTH = 18;
    public static final int AIRDUCTWEST = 19;
    public static final int OTHERCELL = 20;
    public static final int CANTEEN = 21;
    public static final int GYM = 22;
    public static final int OUTISOLATION = 23;
    public static final int DOORISOLATION = 24;
    public static final int ISOLATION = 25;
    public static final int ISOLATIONCORRIDORNORTH = 26;
    public static final int ISOLATIONCORRIDORNORTHNORTH = 27;
    public static final int ISOLATIONCORRIDORNORTHNORTHNORTH = 28;
    public static final int ISOLATIONCORRIDOREAST = 29;
    public static final int ISOLATIONCORRIDOREASTEAST = 30;
    public static final int ISOLATIONCORRIDOREASTEASTEAST = 31;
    public static final int ISOLATIONCORRIDORSOUTH = 32;
    public static final int ISOLATIONCORRIDORSOUTHSOUTH = 33;
    public static final int ISOLATIONCORRIDORSOUTHSOUTHSOUTH = 34;
    public static final int BROTHERCELL = 35;
    public static final int ENDGAME = 36;
    public static final int WINDOWINFIRMARY = 37;
    public static final int FRONTBENCH = 38;
    public static final int BRAWL = 39;
}
